=== RTRUmmadi/ConvertingXSDFile/ConvertingXSDFile/Employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:tns="http://www.example.org/Employee/" 
targetNamespace="http://www.example.org/Employee/">
    <xs:element name="Employee" type="tns:Employee"></xs:element>
    
    <xs:complexType name="Employee">
    	<xs:sequence>
    		<xs:element name="Id" type="xs:int" maxOccurs="unbounded" minOccurs="1"/>
    		<xs:element name="firstName" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
    		<xs:element name="lastName" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
    		<xs:element name="address" type="tns:addressInfo"
    			maxOccurs="unbounded" minOccurs="1">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="addressInfo">
    	<xs:sequence>
    		<xs:element name="address1" type="xs:string"/>
    		<xs:element name="address2" type="xs:string"/>
    		<xs:element name="city" type="xs:string"/>
    		<xs:element name="State" type="xs:string"/>
    		<xs:element name="zipCode" type="xs:string"/>
    	</xs:sequence>
    </xs:complexType>
</xs:schema>

=== RTRUmmadi/ConvertingXSDFile/ConvertingXSDFile/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Employee xmlns:tns="http://www.example.org/Employee/" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/Employee/ Employee.xsd ">
  <Id>1</Id>
  <firstName>Prudhviraj</firstName>
  <lastName>undavalli</lastName>
  <address>
    <address1>address1</address1>
    <address2>address2</address2>
    <city>city</city>
    <State>State</State>
    <zipCode>zipCode</zipCode>
  </address>
</tns:Employee>
